name: End-to-end tests

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWKS_PATH: "/tmp/jwks.json"
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: api-auth
          POSTGRES_PASSWORD: api-auth
          POSTGRES_DB: api-auth
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - name: Install Cypress
        run: npm install cypress@9
      - name: Generate the JWKS file
        run: npm run generate-keystore
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: http://localhost:3000/users/start-sign-in
          build: npm run build
          start: npm start
          install: false
        env:
          OIDC_PAIRWISE_IDENTIFIER_SALT: salt
          SESSION_COOKIE_SECRET: yolo
          PGUSER: api-auth
          PGPASSWORD: api-auth
          PGDATABASE: api-auth
          PGPORT: "5432"
          SECURE_COOKIES: "false"
          DATABASE_URL: "postgres://api-auth:api-auth@localhost:5432/api-auth"
          DO_NOT_SEND_MAIL: "False"
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          INSEE_CONSUMER_KEY: ${{ secrets.INSEE_CONSUMER_KEY }}
          INSEE_CONSUMER_SECRET: ${{ secrets.INSEE_CONSUMER_SECRET }}
          NODE_ENV: production
          CYPRESS_MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          DO_NOT_VALIDATE_MAIL: "True"
      # Store tests runs in case of failure
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
